#!/bin/csh -f

if ( ! -e intersection.out ) then
   echo File \"intersection.out\" not found.
   exit 1
endif

if ( { diff -w intersection.out intersection.sol } ) then
   echo "PROGRAM ACCEPTED."
else
   echo "WRONG OUTPUT."
endif

